[settings]
experimental = true

[tools]
node = "lts"
pnpm = "latest"
python = "3.12"
# rust = "latest"
# "cargo:cargo-binstall" = "latest"
# "cargo:eza" = "latest"
# "cargo:ubi" = "latest"
# "ubi:goreleaser/goreleaser" = "latest"
# "ubi:ajeetdsouza/zoxide" = "latest"
# elixir = "latest"
# erlang = "latest"
# go = "latest"
# ruby = "latest"
# bun = "latest"
